- id: 0
  name: 'Camille'
  beginner: false
- id: 1
  name: 'Michael'
  beginner: false
- id: 2
  name: 'Tom'
  beginner: true
- id: 3
  name: 'Erik'
  beginner: false
- id: 4
  name: 'Lars'
  beginner: false
- id: 5
  name: 'Mathijs'
  beginner: true
